# Generated by Django 4.2.1 on 2023-05-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platos',
            old_name='edad',
            new_name='precio',
        ),
    ]
