# Generated by Django 4.2.1 on 2023-05-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platos', '0002_rename_edad_platos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
